[package]
name = "lit-af-rs"
version = "0.1.0"
authors = ["Trey Del Bonis <j.delbonis.3@gmail.com>"]

[[bin]]
name = "rs-af"
path = "main.rs"

[dependencies]
clap = "2.23.0"
reqwest = "0.8.6"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
